setup_project fixes
Signed-off-by: Petar Koretic <petar.koretic@gmail.com>

diff --git a/setup_project b/setup_project
--- a/setup_project
+++ b/setup_project
@@ -1,10 +1,11 @@
 #!/usr/bin/env bash
 
 project_name=$1
-if [ -z project_name ]
+
+if [ -z $project_name ]
 then
-    echo "usage: ./set_name <name of the project>"
-    echo "ie: ./set_name HelloWorld"
+    echo "usage: ./setup_project <name of the project>"
+    echo "ie: ./setup_project HelloWorld"
     exit
 fi
 
@@ -16,10 +17,14 @@ cd -P -- "$(dirname -- "$0")" && pwd -P
 project_file=src/qml-kickstart.pro
 if [ ! -f $project_file ]
 then
-    echo "Project file '$project-file' not found!"
+    echo "Project file \"$project_file\" not found!"
     echo "This script should be ran after a clean clone is done."
     echo "If you haven't done any changes before running this script please file a bug report at
     https://github.com/qaap/qml-kickstart/issues! Thanks!"
+
+    exit 1
 fi
 
 mv $project_file src/$project_name.pro
+
+echo "Project setup finished: use src/$project_name.pro to start"
